name: Release Action
description: Release action with semantic release
author: PlayStudios
inputs:
  repo-token:
    description: GitHub token
    required: true
  clean:
    description: Clean up obsolete release branches
    required: false
  tag-prefix:
    description: The prefix to use for the git tag. Defaults to 'v'.
    default: 'v'
    required: false
  assets:
    description: The glob pattern to use to find assets to upload to the release
    required: false
    default: ''

runs:
  using: node20
  main: index.js
